project_id = "rckbdhmwdhblcfquedsh"

[functions.polymarket-trades]
verify_jwt = false

[functions.polymarket-traders]
verify_jwt = false

[functions.polymarket-wallet-trades]
verify_jwt = false

[functions.polymarket-realtime]
verify_jwt = false
